platform :ios, '11.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

workspace 'Comic Viewer'
project 'Comic Viewer'
project 'ComicKit/ComicKit'

def comicPods
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'PromiseKit'
    pod 'SwiftyJSON'
    pod 'SwiftHash'
end

abstract_target 'comics' do

    comicPods

    target 'Comic Viewer' do
        project 'Comic Viewer'
        target 'Comic ViewerTests' do
            inherit! :search_paths
        end
        
    end

    target 'ComicKit' do
        project 'ComicKit/ComicKit'
        target 'ComicKitTests' do
            inherit! :search_paths
        end
    end
end
